algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2023
// Seção de Declarações 
var
pes,jarda,milha,polegadas:real
inicio
// Seção de Comandos
escreval ("Digite sua medida em pes")
leia (pes)
 polegadas <- pes * 12;
   jarda <- pes / 3;
   milha <- jarda / 1760;
escreval ("Sua medida em polegadas eh de:", polegadas)
escreval ("Sua medida em jardas eh de:", jarda)
escreval ("Sua medida em milhas eh de:", milha)
fimalgoritmo
