algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2023
// Seção de Declarações 
var
a,b,c,d:real
media:real
inicio
      // Seção de Comandos
      escreval ("Digite 4 numeros")
      leia (a)
      leia(b)
      leia(c)
      leia(d)
       procedimento fazer_medias ()

      var

      inicio
            media <- (a + b + c + d) /4
             escreval(" A media dos 4 numeros foi de: ", media)
      fimprocedimento

fazer_medias()

fimalgoritmo
