algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2023
// Seção de Declarações 
var

inicio
// Seção de Comandos 
procedimento calculo_idade()
var ano_nasc, ano_atual, idade:inteiro
inicio
escreva("Informe o ano de nascimento: ")
leia(ano_nasc)
escreva("Informe o ano atual: ")
leia(ano_atual)
idade <- ano_atual-ano_nasc
escreval ("A idade em anos eh: ",idade)
fimprocedimento
calculo_idade()
fimalgoritmo
